### ISSUE TITLE
Data versioning

### ISSUE THREAD

**Issue by c42f** [JuliaDynamics/DrWatson.jl#37] opened 2019-04-18 03:31 UTC
Plain `git` repos are great for code, but really not so great for large amounts of data. For versioning data, the standard approach is to version only the hashes and store the actual data elsewhere. There's various tools to do this, most notably git-lfs and git-annex.

I wondered whether you have given some thought to this, and wanted to point you in the direction of two very interesting projects which might serve as additional inspiration:

* gin - a radically simple versioning tool for research data with web interface and local tooling https://web.gin.g-node.org/
* Datalad - a power user's tool for versioning datasets https://www.datalad.org/

Both of these are built on top of git and git-annex, but hide some of the complexity of using those low level tools directly. Personally I think gin might be interesting to you as they are really trying to *simplify* the problem of curating scientific datasets, and your mission for DrWatson seems to be to keep it as simple as possible.

**Comment by Datseris** [comment] 2019-04-18 10:18
Yeah, as you said, the mission with DrWatson is to keep things as simple as possible. And DrWatson is not so much a data management system, but a "scientific project assistant" let's say.

Thanks a lot for sharing these. We are currently thinking of porting CaosDB to Julia however this are valid alternatives to consider. @mauro3 was also kind to point out (on discourse) that DataLad is based on Git and could be a better alternative for Julians. These are all very good points to consider and I will also discuss them further with my colleagues that developed CaosDB.

**Comment by c42f** [comment] 2019-04-23 03:41
Very interesting thanks - I haven't seen CaosDB before. It seems several groups are trying to solve parts of the RDMS problem and related problems right now.

I think git and git-annex are a useful substrate which can solve the underlying data versioning problem. The distributed approach is attractive because it allows porting the data between infrastructure. A dataset can be moved between heterogeneous compute environments and outlive the infrastructure on which it was originally acquired / generated / hosted without heroic porting efforts. (Perhaps this is a bit of a situational bias because I'm currently at a small institution where the operational support for data infrastructure is limited.)

For the projects I'm dealing with now there's a few layers which seem to be needed on top of a versioning system. One is data structuring. (The neuroimaging community have attacked this problem by developing a domain-specific community standard called BIDS - see https://bids.neuroimaging.io.) I think the CaosDB paper is interesting because it breaks the schema problem down into two parts:

* The CaosDB data model as a kind of general foundation for scientific-data-as-documents
* Schemas built on top of this, specific to particular domains or projects.

It would be interesting if the paper had more detail on how practical use in scientific projects put constraints on the data model and shaped its design.

There's at least another couple of layers (probably not interesting for DrWatson per se)
* Fast search and access to data from existing projects
* Flexible access control. (Ugh! This is the really hard/ugly part if the versioning substrate is distributed.)

**Comment by salexan2001** [comment] 2019-04-23 12:39
Yes, that's right, CaosDB was designed (I'm one of the developers) with a very strong focus on structuring and searching data in a flexible way. It actually does not really care about how (and where) the data are stored, so we also consider this to be another layer that should be covered by different software.

In fact, I think git-annex is a great approach for managing data in a distributed fashion. Unfortunately many people find it hard to use it, so uptake seems to be really slow (e.g. support for git-annex in gitlab was dropped).

Another approach for managing distributed data is by assigning persistent handles (like the doi system for scientific journals). There is actually one service provided by our local scientific computing center (https://www.gwdg.de/application-services/persistent-identifier-pid) and we are thinking about providing a CaosDB-interface for this service.

**Comment by c42f** [comment] 2019-04-24 07:37
> In fact, I think git-annex is a great approach for managing data in a distributed fashion. Unfortunately many people find it hard to use it, so uptake seems to be really slow

Right, I don't think it's realistic to expect people to use `git-annex` directly (heck, I don't think it's reasonable to expect people producing scientific data to use `git` directly either!). But it seems that wrapping it up could be very promising.

**Comment by Datseris** [comment] 2019-05-11 08:04
Closing this now. I've tried to make it as clear as possible in the documentation that DrWatson is not a data management system.

We have started working on: https://github.com/JuliaDynamics/CaosDB.jl as well, which was mentioned here.

**Closed by Datseris** 2019-05-11 08:04 UTC
Labels: data, discussion

**Comment by c42f** [comment] 2019-05-11 08:36
Sure, thanks for the discussion.
