### ISSUE TITLE
Setting DEFAULT_PATHS

### ISSUE THREAD

**Issue by xukai92** [JuliaDynamics/DrWatson.jl#122] opened 2020-02-07 03:22 UTC
It would be nice to change . One way is simply changing https://github.com/JuliaDynamics/DrWatson.jl/blob/master/src/project_setup.jl#L189-L196 

from
```julia
const DEFAULT_PATHS = [
"_research", "src", "scripts",
"plots", "notebooks",
"papers",
joinpath("data", "sims"),
joinpath("data", "exp_raw"),
joinpath("data", "exp_pro"),
]
```
to 
```julia
const DEFAULT_PATHS = Ref([
"_research", "src", "scripts",
"plots", "notebooks",
"papers",
joinpath("data", "sims"),
joinpath("data", "exp_raw"),
joinpath("data", "exp_pro"),
])
```

Then users can change it by `DrWatson.DEFAULT_PATHS[] = ...`.

There might be better approach though.

**Comment by Datseris** [comment] 2020-02-07 09:22
It is not clear to me what you are asking...

* _What_ would be nice to change? The default paths from a vector to a ref vector?
* _Why_ it would be nice?

At the moment doing changes in `DrWatson.DEFAULT_PATHS` is still possible, since the vector is mutable...? What is the benefit of adding the `Ref` ?


---

Related with the discussion in #2 (I guess).

**Comment by sebastianpech** [comment] 2020-02-07 12:48
Assigning variables in other modules is not allowed. However, if you have `Ref` you can do it because you're not changing the assignment. This allows to change all the default paths at once.

Currently what you can do is using `empty!(DrWatson.DEFAUTL_PATH)` and then `append!(DrWatson.DEFAULT_PATHS,["foo","bar"])`.

**Comment by Datseris** [comment] 2020-02-07 12:57
Okay I see your point(s), but in my eyes this is much better resolved by resolving #2 and making the project setup functionality to be optionally configurable from the user end. 

The `Ref` solution doesn't satisfy me, seems to be not in the same level of quality as the rest of DrWatson...

We could somehow allow `project_setup` to take as default input the current `DEFAULT_PATHS`. The problem is what would happen with the `intro.jl` file. It serves no real purposes, but it is really _fancy_ to see your project name in the Julia script and to all work with `@quickactivate`. And I never underestimate the power of fancyness to impress people.... ;)

**Comment by sebastianpech** [comment] 2020-02-07 13:18
Yeah, I think so too. However, how would a user define the default paths? If you settled on a new set of defaults, I don't think one would always overload them to `initialize_project`.

Just an idea:
How about defining a dict that the user can add paths to. So like
```
DrWatson.USER_PATHS["templateA"] = [....]
DrWatson.USER_PATHS["templateB"] = [....]
```
This can be done from the `config/startup.jl` so it's always available. And if you call `project_initialize` and the dict has elements in it, the user is prompted with a radio menu from `REPL.TerminalMenus` and can select a folder setup.
```
Select a folder setup:
^  DrWatson
 > templateA
v  templateB
```
About the `intro.jl`. I would't force someone to have a scripts directory if I offer those user defined template. How about adding it to the readme or inside the root directory if it can't be placed?

**Comment by Datseris** [comment] 2020-02-07 14:48
Hm, okay I kind of like this approach. We could make it an envinronment variable.

E.g. `ENV["DRWATSON_PATHS"]` . If this is empty, we use the `DrWatson` version. if it is not, we do what you show above.

The benefit of having this in the `ENV` is that DrWatson doesn't have to be installed or used in the general Julia envinroment. 

---

For the intro file, I guess I am overestimating its use then. Of course it is obvious that no user would actually use it, but I thought it was cool to have.

**Comment by sebastianpech** [comment] 2020-02-07 14:51
> For the intro file, I guess I am overestimating its use then. Of course it is obvious that no user would actually use it, but I thought it was cool to have.
I think it's nice to have for beginners.

> We could make it an envinronment variable.
I don't think you can store anything besides strings in there.

**Comment by Datseris** [comment] 2020-02-07 14:59
> I don't think you can store anything besides strings in there.

Yeap, you are correct unfortunately. A better alternative than `DrWatson.USER_PATHS` is `DrWatson.PROJECT_PATHS` I think, as it more clearly indicates what it is.

**Comment by sebastianpech** [comment] 2020-02-07 15:26
It seems to be the only option.
What about the gitignore file? Currently it's tailored to our default folders.

**Comment by Datseris** [comment] 2020-02-07 15:30
darn, problems problems! Yeah I don't know about the `gitingore`, but I would prefer to not over complicate things and leave it as is... manual configuration at every time would make more sense I feel.

**Comment by sebastianpech** [comment] 2020-02-07 15:37
Yeah. Or we actually go with the TOML or YAML file proposed in #2. I used TOML before, it's really simple and readable and the reader parses it into a dict. We could have an extra option for adding a folder to gitignore.
Users could then specify a path in `ENV` to their TOML/YAML config file. Still this might complicate things.

Alternatively we could populate the gitignore with our folders only if the default template is used and the rest is manual config then.

**Comment by Datseris** [comment] 2020-02-07 15:55
I think this is all becoming too complicated, as much complicated as other software that served as "inspiration" for DrWatson (inspiration in the sense "damn, this shouldn't be so complicated!"). Let's not fall into the same trap. 

I believe the current proposal (vector of strings as entry to a dictionary) is as simple as it can get. It also seems to me that setting up your own project structure is such an advanced functionality that the user can worry about the `gitingore` on their own...

But I am having second thoughts about this. All the functionality around `projectdir(), datadir()` and company truly revolves around this project setup. Why change it? Should we even be defining new `somefolderdir()` functions for every different project template?

In fact, now have triple second thoughts about this. What is the benefit? If @xukai92 or @sebastianpech think that the current project structure is not the best, should we just try to improve it instead of allowing a whole zoo of project structures? Isn't one of the main goals of DrWatson to provide a robust, secure, well-thought out project layout that you can use in all your projects and use `datadir()` without a worry in the world?

I am not so sure anymore of the benefits, @xukai92 or @sebastianpech or whoever is interested in this, please provide your arguments on why this is a good thing to do. I'd like to hear them.

**Comment by sebastianpech** [comment] 2020-02-07 16:17
> But I am having second thoughts about this. All the functionality around projectdir(), datadir() and company truly revolves around this project setup. Why change it? Should we even be defining new somefolderdir() functions for every different project template?

Oh, you're right, that's a no-go.

> Isn't one of the main goals of DrWatson to provide a robust, secure, well-thought out project layout that you can use in all your projects and use datadir() without a worry in the world?

Yes definitely, let's keep that in mind. I'm really good with the structure. All I do is sometimes edit the gitignore. Besides that I really like having consistency.

Maybe the best thing if you need an alternative structure is
1. create a project
2. adapt to your needs (With the latest addition of defaults #118 you can also implement new functions for folder retrieval eg add `mynewdir(args...) = projectdir("mynewdir",args...)` to your module)
3. Save that folder somewhere
4. Copy the folder and change the name in the project.toml and of your module file in the src folder

**Comment by xukai92** [comment] 2020-02-17 17:20
> I am not so sure anymore of the benefits, @xukai92 or @sebastianpech or whoever is interested in this, please provide your arguments on why this is a good thing to do. I'd like to hear them.

I come up this issue because I'd like to have my results in a seperate folder rather than (probably) the recemanded `data/results`. But as @sebastianpech pointed out, I can always do this by myself.

**Closed** 2020-02-17 18:01 UTC
