### ISSUE TITLE
Saving dataframe generated by collect_results!

### ISSUE THREAD

**Issue by mbruna** [JuliaDynamics/DrWatson.jl#271] opened 2021-07-24 21:18 UTC
**Describe the bug**
Collect_results! returns a fatal error, but I'm not sure why as it seems to be doing the right thing (I can see the summary file results_(foldername).jld2). However, the file seems empty and doesn't load. Apologies in advance if this is not a DrWatson bug, I'm not quite sure if it's to do with saving as a JLD2.

**Minimal Working Example**
Even the example of collect_results! in the documentation (https://juliadynamics.github.io/DrWatson.jl/stable/real_world/#Listing-completed-runs-1) shows the same behaviour:
```
using DrWatson

general_args = Dict(
    "model" => ["barkley", "kuramoto"],
    "noise" => 0.075,
    "noisy_training" => [true, false],
    "N" => [100],
    "embedding" => [ #(γ, τ, r, c)
    (4, 5, 1, 0.34), (4, 6, 1, 0.28)]
)

function cross_estimation(data)
    γ, τ, r, c = data["embedding"]
    N = data["N"]
    # add fake results:
    data["x"] = rand()
    data["error"] = rand(10)
    # Save data:
    prefix = datadir("results", data["model"])
    get(data, "noisy_training", false) && (prefix *= "_noisy")
    get(data, "symmetric_training", false) && (prefix *= "_symmetric")
    sname = savename((@dict γ τ r c N), "jld2")
    mkpath(datadir("results", data["model"]))
    save(datadir("results", data["model"], sname), data)
    return true
end

dicts = dict_list(general_args)
map(cross_estimation, dicts)

using DataFrames
bl = ["error"]
res = collect_results!(datadir("results"); black_list = bl, subfolders = true)
```
The error I get is:
```
[ Info: Starting a new result collection...
[ Info: Scanning folder /Documents/TestProject/data/results for result files.
[ Info: Added 4 entries.
Error encountered while save FileIO.File{FileIO.DataFormat{:JLD2},String}("/Documents/TestProject/data/results_results.jld2").

Fatal error:
ERROR: ArgumentError: keys must be strings (the names of variables), got df
```
No errors if I run instead
```
res = collect_results(datadir("results"); black_list = bl, subfolders = true)
```

Please also provide the version of `DrWatson` you have installed and your Julia version.
DrWatson version = "2.1.1", julia = "1.4.2"

**Comment by Datseris** [comment] 2021-07-25 15:57
This seems like a bug on our end, but probably @JonasIsensee knows how to fix it. I already checked the name we give to the variable in `collect_results!` here: 

https://github.com/JuliaDynamics/DrWatson.jl/blob/b057ab0724c8cb6450d0d6495fc43f8d3acf32bb/src/result_collection.jl#L119

but it's already a string, `"df"`, so not sure where the issue is coming from.

**Comment by JonasIsensee** [comment] 2021-07-25 16:08
Hi,
I tried your code in a clean julia session using `DrWatson v2.1.1` and `julia v1.7.0-beta3` and it ran without errors.

**Comment by Datseris** [comment] 2021-07-25 16:16
Can confirm on Julia 1.6.

**Comment by Datseris** [comment] 2021-07-25 16:17
Closing for now; if @mbruna can point to a MWE that shows a problem with DrWatson, please do re-open.

**Closed by Datseris** 2021-07-25 16:17 UTC
Labels: bug, running-listing
