### ISSUE TITLE
treatment of floating points in savename

### ISSUE THREAD

**Issue by kyungminlee** [JuliaDynamics/DrWatson.jl#163] opened 2020-06-10 17:38 UTC
When the value of a parameter is a float, `savename` checks if it can be rounded to an integer. This is good for keeping the filename short. But at the same time, it makes it cumbersome to work with the filename outside of DrWatson (e.g. checking whether the file exists in shell, etc.). I wonder if it may be a good idea to add an optional argument that controls the number of digits for floating points.

**Comment by JonasIsensee** [comment] 2020-06-13 06:35
Yeah, tbh the automatic type conversion has also made me feal uneasy every time I came across it.

Maybe it is not necessary to make it a default but if I had the option to _not_ automatically convert whole-number floats then I would definitely use it.

@Datseris I understand that the current implementation works well for you but different people have different constraints/requirements and I think it would be worth an extra keyword argument
to provide a *simpler-to-reproduce-in-another-language* behaviour.
Also in general for readability I think this feature of *fixed number of digits* might be useful
since the output strings would have the same length

**Comment by Datseris** [comment] 2020-06-13 08:13
sure, but then no 2 keywords are needed, only one, this "length". And then, what does the keyword `digits` have use for? The length is also the digits you round if possible.

**Comment by tamasgal** [comment] 2020-06-13 08:23
Funnily I have not stumbled upon the `x.0 -> x` conversion yet, but I also think that this is confusing (from the docs of `savename`):

```julia
savename(d; digits = 4) == "a=0.1535_b=5_mode=double"
```

In my opinion `digits` should enforce the "length" and the automatic conversion should not take place at least when `digits` is used.

I of course know that this is documented but I think it's  not intuitive:

```julia
    •    digits = 3 : Floating point values are rounded to digits. In addition if the following holds:
      
        round(val; digits = digits) == round(Int, val)
  
          then the integer value is used in the name instead.
```

I understand that the main purpose is human readability but since we are physicists, we all know that `1 != 1.0` in the sense that second carries a different information about the precision, as well as `1.0 != 1.00` etc.

So what about "if digits then no int-conversion"?

**Comment by Datseris** [comment] 2020-06-13 08:26
You all convinced me for this change, making `digits` explicitly write down the necessary/required digits for floating point numbers. My only standing concern is that it is "technically" a breaking change.

**Comment by tamasgal** [comment] 2020-06-13 08:30
OK what about setting `digits = nothing` by default and if `digits == nothing`, set it to `3` and turn on the automatic int-conversion.

Note that this `parameter = nothing` but still having a specific default value is quite common in Julia base. The same approach is used in many Python projects either, where the `parameter=None` and then `if parameter == None: parameter = default_value`...

**Comment by Datseris** [comment] 2020-12-16 02:18
c.f. also https://github.com/JuliaDynamics/DrWatson.jl/issues/220 which I closed in favor of this one, as they fall into the same topic.

**Comment by sebastianpech** [comment] 2021-03-01 20:23
@Datseris @tamasgal Why are we doing the int conversion again? Because this case from #232 
```
julia> 2.1e11
2.1e11

julia> savename(Dict(:a=>2.1e11),scientific=3)
"a=210000000000"
```
is not concise or easily readable at all. Could we change the int conversion to instead convert both the scientific rounding (if requested) and the int rounding to a string and then compare the length and print the shorter one?

Replacing this:
https://github.com/JuliaDynamics/DrWatson.jl/blob/master/src/naming.jl#L153-L154

**Comment by Datseris** [comment] 2021-03-01 21:49
Okay we should change this to *NOT* do the Float -> Int conversion, nobody likes it. I guess I didn't think it throughou when I wrote the function years ago, back then I thought it would a "good idea". The question is, does this warrant a 2.0, or simply an update message is enough?

**Comment by Datseris** [comment] 2021-03-01 21:50
If we think about it, it might not be breaking in the sense that if a user used `savename` to create a file name to be saved, they most likely again used `savename` to create a file name to be loaded.

**Comment by PetrKryslUCSD** [comment] 2021-03-01 21:53
I want to point out that an option to produce the engineering floating-point representation (with an exponent) is quite crucial. I don't think that by "scientific" you mean the same thing.

**Comment by sebastianpech** [comment] 2021-03-02 06:51
@Datseris 
> If we think about it, it might not be breaking in the sense that if a user used savename to create a file name to be saved, they most likely again used savename to create a file name to be loaded.

Well I mean it does break `produce_or_load`, at least the first time after the update. Alternatively, we could add a new keyword for doing the exponential representation. Yesterday I noticed that just `scientific` is a bit confusing. This way we can still keep the old behavior, break nothing at the moment, and remove it later with 2.0.

@PetrKryslUCSD 
> I want to point out that an option to produce the engineering floating-point representation (with an exponent) is quite crucial. I don't think that by "scientific" you mean the same thing.

Can you elaborate on what you mean? I think the intention is the same, it just currently doesn't work.

**Comment by PetrKryslUCSD** [comment] 2021-03-02 15:09
Well, it did not work, so I assumed I misread the documentation, and that the intention was to simply round:
```
julia> savename("sim", (b=b, ); scientific=5)
"sim_b=0.58671"

julia> b
0.5867127817931002
```
I think you are saying that it is supposed to work, but it is broken?

**Comment by sebastianpech** [comment] 2021-03-02 15:34
@PetrKryslUCSD It's doing what it's supposed to do in the case you showed. Converting a float in Julia is always done under two considerations: As short as possible and as precise as possible. (This is likely an oversimplification, I remember the algorithm is explained somewhere in the docs).

So in your case, you round to 5 significant digits `58671`. Scientific or engineering notation always adds at least 2 more digits eg. `e7`. In case your number is actually smaller than 1 you get at least 3 more digits eg. `e-3`. So as long as you don't have enough leading or trailing zeros, Julia won't show your number in scientific notation, because just printing it without the additional `e` is shorter.

```
1.0e-1 # My input
0.1  # Repl output

1.0e-2
0.01

1.0e-3
0.001

1.0e-4
0.0001

1.0e-5
1.0e-5

1.0e1
10.0

1.0e2
100.0

1.0e3 #The alg. for numbers larger than 1 is a bit different, maybe due to readability.
1000.0

1.0e4
10000.0

1.0e5
100000.0

1.0e6
1.0e6
```

And this is what we use. So you get the scientific notation for the following number:
```
julia> savename("sim", (b=0.000032, ); scientific=5)
"sim_b=3.2e-5"
```

It is "broken" for positive numbers though
```
julia> savename("sim", (b=10000000., ); scientific=5)
"sim_b=10000000"

julia> 10000000.
1.0e7
```

**Comment by PetrKryslUCSD** [comment] 2021-03-02 15:37
Indeed:
```
julia> b = 2e11
2.0e11

julia> savename("sim", (b=b, ); scientific=2)
"sim_b=200000000000"
```
This was actually my original example.

**Comment by PetrKryslUCSD** [comment] 2021-03-02 15:38
So is the case of large positive numbers a WIP?

**Comment by sebastianpech** [comment] 2021-03-02 15:40
It's a really simple change, however, it could break some of the users' code so we are still discussing.

**Comment by Datseris** [comment] 2021-03-02 15:47
Let's move all requests to the ongoing PR #233 please! This will most likely necessitate a 2.0...

**Comment by PetrKryslUCSD** [comment] 2021-03-02 15:51
These long strings of zeros are illegible. I would very much prefer the option of using a keyword to achieve a clearly formatted name. That is, if you decide you don't want to break existing functionality.

**Closed** 2021-03-08 19:00 UTC
Labels: enhancement, savename
