### ISSUE TITLE
Saving files with long names.

### ISSUE THREAD

**Issue by ignace-computing** [JuliaDynamics/DrWatson.jl#219] opened 2020-12-07 14:41 UTC
Hello!

When you have a lot of simulation parameters, the filename under which you want to save your data mighty become too long. Here is a minimal working example of such a situation:

<code>long_word = "thisIsAVeryLongWordAndItCanBeEvenLonger"</code>
<code>very_long_dict = Dict(:long_word => long_word, :a=>0.123)</code>
<code>very_long_dict[:other_long_word] = long_word*long_word</code>

<code>dict_with_results = Dict(:niceresults => true)</code>
<code>DATADIR_NAME = "testDir"</code>

<code>wsave(datadir(DATADIR_NAME, savename(very_long_dict, "bson")), dict_with_results)</code>

That gives the following error:
<code>IOError: stat: name too long (ENAMETOOLONG) for file ...</code>

Would you have any ideas? 
Thank you.

**Comment by Datseris** [comment] 2020-12-07 15:06
Hi!

Limits of filenames come from the operating system, so my only suggestion is "reduce name size".

(this is also why this question is unrelated to DrWatson)

**Comment by ignace-computing** [comment] 2020-12-09 18:17
Thank you for the response.
I understand why you closed the issue and also why you think it is unrelated.

However, I must say that, in real life, simulations often simply contain a lot of input parameters. It would be nice if DrWatson had an extra functionality, where it automatically maps a long file name onto a shorter one (and of course also does the bookkeeping, probably with a new [bidirectionally searchable] data structure mapping short names to longer ones).

So, yes this is an operating system issue, but I think it would be nice if DrWatson provides us with robust tools to circumvent it. Any ideas on how this could be implemented?

All the best,

**Comment by tamasgal** [comment] 2020-12-09 18:25
I think the root of the problem is to squeeze a lot of information into the filename. I personally do not like putting information into the filename but rather use a local database or table to find meta data for my files. For simple things where you scan a parameter space for a few variables, the `savename`-approach is perfectly fine, but for anything which goes beyond that (and your example certainly does), you should think about a proper meta-data management.

That being said, if you have a use-case and you think you can generalise it, we are happy to discuss it in a PR! `:)`

**Comment by Datseris** [comment] 2020-12-09 18:34
> It would be nice if DrWatson had an extra functionality, where it automatically maps a long file name onto a shorter one (and of course also does the bookkeeping, probably with a new [bidirectionally searchable] data structure mapping short names to longer ones).

That's an interesting suggestion. I've closed this issue because you haven't said any of this beforehand, and I simply consider the issue an incorrect bug report, I didn't mean to disregard the suggestion.

However, I agree with Tamas' statement here. It is probably more useful to use a proper database, otherwise things might get out of hand quickly... DrWatson is not a data-management system (because e.g. we're getting CaosDB.jl soon in Julia), which is why I'd feel reluctant adding database-management-functionality here.

**Comment by omerchiers** [comment] 2020-12-17 10:48
> I think the root of the problem is to squeeze a lot of information into the filename. I personally do not like putting information into the filename but rather use a local database or table to find meta data for my files. For simple things where you scan a parameter space for a few variables, the `savename`-approach is perfectly fine, but for anything which goes beyond that (and your example certainly does), you should think about a proper meta-data management.

Probably it's not the best place to discuss this, but I would be very interested in seeing such a metadata management workflow. Maybe we could move that part of the discussion to discourse?

**Comment by Datseris** [comment] 2021-02-09 14:19
Yes, sounds like the most reasonable.

**Closed by Datseris** 2021-02-09 14:19 UTC
Labels: data, discussion

**Comment by Uroc327** [comment] 2021-07-27 17:57
Do you happen to have a link to the discussion regarding metadata/simulation-param mangement in a separate database? I'd also be interest in indexing my simulations when I have too many parameters to have them all in a filename.

**Comment by Datseris** [comment] 2021-07-27 20:45
Have a look at: https://github.com/sebastianpech/DrWatsonSim.jl  perhaps @sebastianpech can point you to other discussions that have taken place (I do not remember at the moment, sorry)

**Comment by sebastianpech** [comment] 2021-07-27 20:54
@Uroc327 I'm not sure where we had the discussion. But if you're looking for metadata capabilities try DrWatsonSim.jl. You don't need to use the simulation part, metadata works without it. Usage is explained in the readme (https://github.com/sebastianpech/DrWatsonSim.jl#adding-metadata)

**Comment by sebastianpech** [comment] 2021-07-27 21:00
@Uroc327 This was the discussion https://github.com/JuliaDynamics/DrWatson.jl/issues/151
The interesting stuff about metadata with DrWatsonSim is at the end

**Comment by omerchiers** [comment] 2021-07-27 21:12
Following my own suggestion higher up, I started a topic on discourse [here](https://discourse.julialang.org/t/examples-of-a-database-to-manage-simulation-result-files/55063?u=olivier_merchiers).
A few interesting suggestions were made but I didn't have time to implement anything myself. So I think indeed that, as suggested by sebastianpech, DrWatsonSim.jl is probably your best option right now.

**Comment by Uroc327** [comment] 2021-07-28 08:30
Thanks for the links. As I rely on the loading part of `produce_or_load` a lot right now, I decided to shorten the parameter names for now.
